ARG BASE_IMAGE=ubuntu:22.04
# Look for build time variable, if not defined default to ubuntu 22.04
FROM ${BASE_IMAGE}

# Remapping of isaac Ros packages names to Ros 2 packages
COPY src/isaac_ros_common/docker/rosdep/extra_rosdeps.yaml /etc/ros/rosdep/sources.list.d/nvidia-isaac.yaml

# Increase Cyclone socket size for big ROS2 message exchanges
ENV CYCLONEDDS_URI="file:///workspaces/isaac_ros-dev/src/isaac_ros_common/scripts/cyclone_config.xml"

# For Isaac rosdep
RUN echo "yaml file:///etc/ros/rosdep/sources.list.d/nvidia-isaac.yaml" \
                > /etc/ros/rosdep/sources.list.d/00-nvidia-isaac.list

# Otherwise CMake errors: `setuptools_scm._file_finders.git listing git files failed - pretending there aren't any`
RUN pip3 uninstall setuptools-scm -y

# ZED SDK installation
COPY src/isaac_ros_common/docker/scripts/docker_install-zed-x86_64.sh opt/zed/install-zed-x86_64.sh

RUN chmod +x opt/zed/install-zed-x86_64.sh && \
    opt/zed/install-zed-x86_64.sh

RUN chmod -R 777 /usr/local/zed

# Rosdep
RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=bind,source=./src/ag_tech_ros/config/rosdep_collection,target=/workspaces/isaac_ros-dev/src \
    apt-get update && \
    rosdep update && \
    rosdep install \
        --from-paths /workspaces/isaac_ros-dev/src \
        --ignore-src -y

# # NPM
# RUN --mount=type=cache,target=/var/cache/apt \
#     curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash - && \
#     apt-get install -y nodejs && \
#     npm install -g @openai/codex